spring.application.name=crud-usurario

# Configurações do Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações da Conexão com o Banco (Corrigido de spring.h2.datasource para spring.datasource)
spring.datasource.url=jdbc:h2:mem:usuario
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Mikhail
spring.datasource.password=123